package gitlet;

import java.io.File;
import java.io.Serializable;

import static gitlet.MyUtils.*;
import static gitlet.Utils.*;
import static gitlet.Repository.*;

/**
 * A Blob object represents a snapshot of a single file's content.
 * It stores the file name, raw bytes, and a unique id (SHA-1 hash).
 */
public class Blob implements Serializable {

    /** Generated by file content, uniquely identifies this blob (SHA-1 hash). */
    private String id;
    /** The name of the original file. */
    private String fileName;
    /** File contents in bytes. */
    private byte[] bytes;

    /**
     * Create a Blob from a given File.
     * The id is computed from file name + bytes + "Blob".
     */
    public Blob(File file) {
        fileName = file.getName();
        bytes = Utils.readContents(file);
        id = Utils.sha1(fileName, bytes, "Blob");
    }

    /**
     * Factory method to create and immediately save a Blob.
     * @param file The source file
     * @return the created Blob instance
     */
    public static Blob creBlob(File file) {
        Blob blob = new Blob(file);
        blob.saveBlob();
        return blob;
    }

    /** Convenience constructor: create a Blob using a file path string. */
    public Blob(String filePath) {
        this(new File(filePath));
    }

    /**
     * Save this blob object into the object directory.
     * If the directory does not exist, create it.
     * @return true if file already existed; false if newly created.
     */
    public boolean saveBlob() {
        // Create directory if not exist
        if (!OBJECT_DIR.exists() && !OBJECT_DIR.mkdirs()) {
            throw new IllegalStateException("can't create dir" + OBJECT_DIR.getAbsolutePath());
        }

        File f = join(OBJECT_DIR, id);
        if (f.exists()) {
            writeObject(f, this);
            return true;
        } else {
            writeObject(f, this);
            return false;
        }
    }

    /** Get blob ID. */
    public String getId() {
        return id;
    }

    /** Get the file name represented by this blob. */
    public String getFileName() {
        return fileName;
    }

    /** Get the file's raw bytes. */
    public byte[] getBytes() {
        return bytes;
    }

    /** Get file content as string (for text files). */
    public String getContentAsString() {
        return new String(bytes);
    }

    /**
     * Read a blob object from storage.
     * If the stored object is not a Blob, or id is null, return null.
     */
    public static Blob readBlob(String blobId) {
        if (blobId == null) {
            return null;
        }
        Serializable obj = readSerializable(blobId);
        return (obj instanceof Blob) ? (Blob) obj : null;
    }

    /**
     * Recover (write back) this blob's contents into working directory.
     * The file will be written under current working directory with its name.
     */
    public void recover() {
        writeContents(join(CWD, fileName), (Object) bytes);
    }

    /**
     * Check equality between two Blob instances by comparing their ids.
     * Handles null references safely.
     */
    public static boolean equalsBlob(Blob a, Blob b) {
        if (a == null && b == null) {
            return true;
        }
        if (a == null || b == null) {
            return false;
        }
        return a.getId().equals(b.getId());
    }

    /** Generate hash code consistent with equals(), based on blob id. */
    @Override
    public int hashCode() {
        return (id == null) ? 0 : id.hashCode();
    }

    /** Two blobs are equal if they share the same id. */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (obj instanceof Blob) {
            return ((Blob) obj).getId().equals(this.id);
        }
        return false;
    }

    /** Return a readable description of this blob, including id, name, and content. */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("----\n");
        sb.append("id: ").append(id).append("\n");
        sb.append("fileName: ").append(fileName).append("\n");
        sb.append("content:\n");
        sb.append(new String(bytes));
        sb.append("\n----\n");
        return sb.toString();
    }
}
